# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aki_sign(object):
    def setupUi(self, Aki_sign):
        Aki_sign.setObjectName("Aki_sign")
        Aki_sign.resize(961, 578)
        Aki_sign.setStyleSheet("QMainWindow {\n"
"    border: none;\n"
"    border-radius: 25px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Aki_sign)
        self.centralwidget.setObjectName("centralwidget")
        self.background_main = QtWidgets.QFrame(self.centralwidget)
        self.background_main.setGeometry(QtCore.QRect(10, 10, 941, 561))
        self.background_main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.background_main.setStyleSheet("QFrame {\n"
"    background-color:rgb(24, 24, 24);\n"
"    color:rgb(177, 177, 177);\n"
"    border-radius:  20px;\n"
"    border: None\n"
"}")
        self.background_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_main.setObjectName("background_main")
        self.poloska = QtWidgets.QFrame(self.background_main)
        self.poloska.setGeometry(QtCore.QRect(0, 50, 941, 1))
        self.poloska.setStyleSheet("QFrame {\n"
"    background-color:rgb(33, 33, 33);\n"
"}")
        self.poloska.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.poloska.setFrameShadow(QtWidgets.QFrame.Plain)
        self.poloska.setObjectName("poloska")
        self.btn_close = QtWidgets.QPushButton(self.background_main)
        self.btn_close.setGeometry(QtCore.QRect(910, 15, 16, 16))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    background: transparent\n"
"}")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/aki_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setIconSize(QtCore.QSize(13, 13))
        self.btn_close.setObjectName("btn_close")
        self.img_logo = QtWidgets.QPushButton(self.background_main)
        self.img_logo.setGeometry(QtCore.QRect(20, 15, 24, 24))
        self.img_logo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.img_logo.setStyleSheet("QPushButton {\n"
"    background: transparent\n"
"}")
        self.img_logo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/aki_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.img_logo.setIcon(icon1)
        self.img_logo.setIconSize(QtCore.QSize(18, 18))
        self.img_logo.setObjectName("img_logo")
        self.logo_text = QtWidgets.QLabel(self.background_main)
        self.logo_text.setGeometry(QtCore.QRect(45, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logo_text.setFont(font)
        self.logo_text.setStyleSheet("QLabel {\n"
"    color: #fff\n"
"}")
        self.logo_text.setObjectName("logo_text")
        self.sign_stackedWidget = QtWidgets.QStackedWidget(self.background_main)
        self.sign_stackedWidget.setGeometry(QtCore.QRect(325, 70, 305, 451))
        self.sign_stackedWidget.setStyleSheet("")
        self.sign_stackedWidget.setObjectName("sign_stackedWidget")
        self.auth_page = QtWidgets.QWidget()
        self.auth_page.setStyleSheet("QWidget {\n"
"    background: transparent\n"
"}")
        self.auth_page.setObjectName("auth_page")
        self.auth_frame = QtWidgets.QFrame(self.auth_page)
        self.auth_frame.setGeometry(QtCore.QRect(0, 60, 305, 331))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.auth_frame.setFont(font)
        self.auth_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(19, 19, 19);\n"
"    border:  None;\n"
"    border-radius: 10px\n"
"}")
        self.auth_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.auth_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.auth_frame.setObjectName("auth_frame")
        self.auth_text = QtWidgets.QLabel(self.auth_frame)
        self.auth_text.setGeometry(QtCore.QRect(0, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(16)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.auth_text.setFont(font)
        self.auth_text.setStyleSheet("QLabel {\n"
"    color: #fff\n"
"}")
        self.auth_text.setAlignment(QtCore.Qt.AlignCenter)
        self.auth_text.setObjectName("auth_text")
        self.auth_login = QtWidgets.QLineEdit(self.auth_frame)
        self.auth_login.setGeometry(QtCore.QRect(20, 70, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.auth_login.setFont(font)
        self.auth_login.setStyleSheet("QLineEdit {\n"
"    padding: 45px;\n"
"    border: none;\n"
"    background-color: #0e0e0e;\n"
"    border-radius: 7px;\n"
"    color: #fff\n"
"}")
        self.auth_login.setInputMask("")
        self.auth_login.setObjectName("auth_login")
        self.auth_pass = QtWidgets.QLineEdit(self.auth_frame)
        self.auth_pass.setGeometry(QtCore.QRect(20, 130, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.auth_pass.setFont(font)
        self.auth_pass.setStyleSheet("QLineEdit {\n"
"    padding: 45px;\n"
"    border: none;\n"
"    background-color: #0e0e0e;\n"
"    border-radius: 7px;\n"
"    color: #fff\n"
"}")
        self.auth_pass.setText("")
        self.auth_pass.setObjectName("auth_pass")
        self.remember_me = QtWidgets.QCheckBox(self.auth_frame)
        self.remember_me.setGeometry(QtCore.QRect(20, 178, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.remember_me.setFont(font)
        self.remember_me.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remember_me.setStyleSheet("QCheckBox {\n"
"    border : None;\n"
"    border-radius: 50%;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(149, 158, 201);\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius : 8px;\n"
"    background: rgb(19, 19, 19);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked { \n"
"    background: 3px solid rgb(230, 52, 98);\n"
"    border: 3px solid rgb(230, 52, 98);\n"
#"    background-image: url(:/16x16/icons/aki_check.png);\n"
"}")
        self.remember_me.setObjectName("remember_me")
        self.forgot_pass = QtWidgets.QPushButton(self.auth_frame)
        self.forgot_pass.setGeometry(QtCore.QRect(180, 178, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.forgot_pass.setFont(font)
        self.forgot_pass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgot_pass.setStyleSheet("QPushButton {\n"
"    color: rgb(108, 109,112);\n"
"}")
        self.forgot_pass.setObjectName("forgot_pass")
        self.not_account = QtWidgets.QLabel(self.auth_frame)
        self.not_account.setGeometry(QtCore.QRect(50, 300, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setBold(False)
        font.setWeight(50)
        self.not_account.setFont(font)
        self.not_account.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.not_account.setObjectName("not_account")
        self.auth_reg_btn = QtWidgets.QPushButton(self.auth_frame)
        self.auth_reg_btn.setGeometry(QtCore.QRect(140, 300, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setBold(False)
        font.setWeight(50)
        self.auth_reg_btn.setFont(font)
        self.auth_reg_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.auth_reg_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 52, 98);\n"
"}")
        self.auth_reg_btn.setObjectName("auth_reg_btn")
        self.auth_sign = QtWidgets.QPushButton(self.auth_frame)
        self.auth_sign.setGeometry(QtCore.QRect(20, 230, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.auth_sign.setFont(font)
        self.auth_sign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.auth_sign.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 12.5px;\n"
"    background-color: rgb(230, 52, 98)\n"
"}")
        self.auth_sign.setObjectName("auth_sign")
        self.auth_login_img = QtWidgets.QPushButton(self.auth_frame)
        self.auth_login_img.setGeometry(QtCore.QRect(25, 75, 30, 30))
        self.auth_login_img.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border-radius: 5px\n"
"}")
        self.auth_login_img.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/aki_user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auth_login_img.setIcon(icon2)
        self.auth_login_img.setObjectName("auth_login_img")
        self.auth_pass_img = QtWidgets.QPushButton(self.auth_frame)
        self.auth_pass_img.setGeometry(QtCore.QRect(25, 135, 30, 30))
        self.auth_pass_img.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border-radius: 5px\n"
"}")
        self.auth_pass_img.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/aki_password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auth_pass_img.setIcon(icon3)
        self.auth_pass_img.setObjectName("auth_pass_img")
        self.not_account.raise_()
        self.auth_text.raise_()
        self.auth_login.raise_()
        self.auth_pass.raise_()
        self.remember_me.raise_()
        self.forgot_pass.raise_()
        self.auth_reg_btn.raise_()
        self.auth_sign.raise_()
        self.auth_login_img.raise_()
        self.auth_pass_img.raise_()
        self.sign_stackedWidget.addWidget(self.auth_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setStyleSheet("QWidget {\n"
"    background: transparent\n"
"}")
        self.register_page.setObjectName("register_page")
        self.reg_frame = QtWidgets.QFrame(self.register_page)
        self.reg_frame.setGeometry(QtCore.QRect(0, 0, 301, 451))
        self.reg_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(19, 19, 19);\n"
"    border:  None;\n"
"    border-radius: 10px\n"
"}")
        self.reg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reg_frame.setObjectName("reg_frame")
        self.reg_terms_of_use_check = QtWidgets.QCheckBox(self.reg_frame)
        self.reg_terms_of_use_check.setGeometry(QtCore.QRect(15, 308, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reg_terms_of_use_check.setFont(font)
        self.reg_terms_of_use_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_terms_of_use_check.setStyleSheet("QCheckBox {\n"
"    border : None;\n"
"    border-radius: 50%;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(149, 158, 201);\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius : 8px;\n"
"    background: rgb(19, 19, 19);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked { \n"
"    background: 3px solid rgb(230, 52, 98);\n"
"    border: 3px solid rgb(230, 52, 98);\n"
#"    background-image: url(:/16x16/icons/aki_check.png);\n"
"}")
        self.reg_terms_of_use_check.setObjectName("reg_terms_of_use_check")
        self.have_account = QtWidgets.QLabel(self.reg_frame)
        self.have_account.setGeometry(QtCore.QRect(60, 410, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setBold(False)
        font.setWeight(50)
        self.have_account.setFont(font)
        self.have_account.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.have_account.setObjectName("have_account")
        self.reg_login = QtWidgets.QLineEdit(self.reg_frame)
        self.reg_login.setGeometry(QtCore.QRect(20, 70, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.reg_login.setFont(font)
        self.reg_login.setStyleSheet("QLineEdit {\n"
"    padding: 45px;\n"
"    border: none;\n"
"    background-color: #0e0e0e;\n"
"    border-radius: 7px;\n"
"    color: #fff\n"
"}")
        self.reg_login.setInputMask("")
        self.reg_login.setObjectName("reg_login")
        self.reg_email_img = QtWidgets.QPushButton(self.reg_frame)
        self.reg_email_img.setGeometry(QtCore.QRect(25, 135, 30, 30))
        self.reg_email_img.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border-radius: 5px\n"
"}")
        self.reg_email_img.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/aki_email.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reg_email_img.setIcon(icon4)
        self.reg_email_img.setObjectName("reg_email_img")
        self.reg_login_img = QtWidgets.QPushButton(self.reg_frame)
        self.reg_login_img.setGeometry(QtCore.QRect(25, 75, 30, 30))
        self.reg_login_img.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border-radius: 5px\n"
"}")
        self.reg_login_img.setText("")
        self.reg_login_img.setIcon(icon2)
        self.reg_login_img.setObjectName("reg_login_img")
        self.reg_email = QtWidgets.QLineEdit(self.reg_frame)
        self.reg_email.setGeometry(QtCore.QRect(20, 130, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.reg_email.setFont(font)
        self.reg_email.setStyleSheet("QLineEdit {\n"
"    padding: 45px;\n"
"    border: none;\n"
"    background-color: #0e0e0e;\n"
"    border-radius: 7px;\n"
"    color: #fff\n"
"}")
        self.reg_email.setText("")
        self.reg_email.setObjectName("reg_email")
        self.reg_auth_btn = QtWidgets.QPushButton(self.reg_frame)
        self.reg_auth_btn.setGeometry(QtCore.QRect(185, 410, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setBold(False)
        font.setWeight(50)
        self.reg_auth_btn.setFont(font)
        self.reg_auth_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_auth_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 52, 98);\n"
"}")
        self.reg_auth_btn.setObjectName("reg_auth_btn")
        self.reg_sign = QtWidgets.QPushButton(self.reg_frame)
        self.reg_sign.setGeometry(QtCore.QRect(20, 350, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.reg_sign.setFont(font)
        self.reg_sign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_sign.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 12.5px;\n"
"    background-color: rgb(230, 52, 98)\n"
"}")
        self.reg_sign.setObjectName("reg_sign")
        self.reg_text = QtWidgets.QLabel(self.reg_frame)
        self.reg_text.setGeometry(QtCore.QRect(0, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(16)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.reg_text.setFont(font)
        self.reg_text.setStyleSheet("QLabel {\n"
"    color: #fff\n"
"}")
        self.reg_text.setAlignment(QtCore.Qt.AlignCenter)
        self.reg_text.setObjectName("reg_text")
        self.reg_conditions = QtWidgets.QPushButton(self.reg_frame)
        self.reg_conditions.setGeometry(QtCore.QRect(130, 310, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reg_conditions.setFont(font)
        self.reg_conditions.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_conditions.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 52, 98);\n"
"}")
        self.reg_conditions.setObjectName("reg_conditions")
        self.reg_terms_of_text2 = QtWidgets.QLabel(self.reg_frame)
        self.reg_terms_of_text2.setGeometry(QtCore.QRect(198, 308, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setBold(False)
        font.setWeight(50)
        self.reg_terms_of_text2.setFont(font)
        self.reg_terms_of_text2.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.reg_terms_of_text2.setObjectName("reg_terms_of_text2")
        self.reg_terms_of_use = QtWidgets.QPushButton(self.reg_frame)
        self.reg_terms_of_use.setGeometry(QtCore.QRect(203, 310, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reg_terms_of_use.setFont(font)
        self.reg_terms_of_use.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_terms_of_use.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 52, 98);\n"
"}")
        self.reg_terms_of_use.setObjectName("reg_terms_of_use")
        self.reg_terms_of_use2 = QtWidgets.QPushButton(self.reg_frame)
        self.reg_terms_of_use2.setGeometry(QtCore.QRect(36, 324, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reg_terms_of_use2.setFont(font)
        self.reg_terms_of_use2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_terms_of_use2.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 52, 98);\n"
"}")
        self.reg_terms_of_use2.setObjectName("reg_terms_of_use2")
        self.reg_pass = QtWidgets.QLineEdit(self.reg_frame)
        self.reg_pass.setGeometry(QtCore.QRect(20, 190, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.reg_pass.setFont(font)
        self.reg_pass.setStyleSheet("QLineEdit {\n"
"    padding: 45px;\n"
"    border: none;\n"
"    background-color: #0e0e0e;\n"
"    border-radius: 7px;\n"
"    color: #fff\n"
"}")
        self.reg_pass.setText("")
        self.reg_pass.setObjectName("reg_pass")
        self.reg_pass_img = QtWidgets.QPushButton(self.reg_frame)
        self.reg_pass_img.setGeometry(QtCore.QRect(25, 195, 30, 30))
        self.reg_pass_img.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border-radius: 5px\n"
"}")
        self.reg_pass_img.setText("")
        self.reg_pass_img.setIcon(icon3)
        self.reg_pass_img.setObjectName("reg_pass_img")
        self.reg_pass_2 = QtWidgets.QLineEdit(self.reg_frame)
        self.reg_pass_2.setGeometry(QtCore.QRect(20, 250, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        self.reg_pass_2.setFont(font)
        self.reg_pass_2.setStyleSheet("QLineEdit {\n"
"    padding: 45px;\n"
"    border: none;\n"
"    background-color: #0e0e0e;\n"
"    border-radius: 7px;\n"
"    color: #fff\n"
"}")
        self.reg_pass_2.setText("")
        self.reg_pass_2.setObjectName("reg_pass_2")
        self.reg_pass_img2 = QtWidgets.QPushButton(self.reg_frame)
        self.reg_pass_img2.setGeometry(QtCore.QRect(25, 255, 30, 30))
        self.reg_pass_img2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border-radius: 5px\n"
"}")
        self.reg_pass_img2.setText("")
        self.reg_pass_img2.setIcon(icon3)
        self.reg_pass_img2.setObjectName("reg_pass_img2")
        self.reg_terms_of_use_check.raise_()
        self.have_account.raise_()
        self.reg_login.raise_()
        self.reg_login_img.raise_()
        self.reg_pass.raise_()
        self.reg_auth_btn.raise_()
        self.reg_sign.raise_()
        self.reg_text.raise_()
        self.reg_conditions.raise_()
        self.reg_terms_of_text2.raise_()
        self.reg_terms_of_use.raise_()
        self.reg_terms_of_use2.raise_()
        self.reg_email_img.raise_()
        self.reg_pass.raise_()
        self.reg_pass_img.raise_()
        self.reg_pass_2.raise_()
        self.reg_pass_img2.raise_()
        self.sign_stackedWidget.addWidget(self.register_page)
        self.aki_copyright = QtWidgets.QLabel(self.background_main)
        self.aki_copyright.setGeometry(QtCore.QRect(40, 530, 851, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.aki_copyright.setFont(font)
        self.aki_copyright.setStyleSheet("")
        self.aki_copyright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aki_copyright.setObjectName("aki_copyright")
        self.notifications_dark_background = QtWidgets.QFrame(self.background_main)
        self.notifications_dark_background.setGeometry(QtCore.QRect(0, 0, 941, 561))
        self.notifications_dark_background.setStyleSheet("QFrame {\n"
"    background-color:rgba(24, 24, 24, 0.7);\n"
"    color:rgb(177, 177, 177);\n"
"    border-radius:  20px\n"
"}")
        self.notifications_dark_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notifications_dark_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notifications_dark_background.setObjectName("notifications_dark_background")
        self.notifications_main_background = QtWidgets.QFrame(self.notifications_dark_background)
        self.notifications_main_background.setGeometry(QtCore.QRect(100, 60, 741, 81))
        self.notifications_main_background.setStyleSheet("QFrame {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border:  None;\n"
"    border-radius: 10px;\n"
"}")
        self.notifications_main_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notifications_main_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notifications_main_background.setObjectName("notifications_main_background")
        self.notifications_up = QtWidgets.QFrame(self.notifications_main_background)
        self.notifications_up.setGeometry(QtCore.QRect(0, 0, 741, 51))
        self.notifications_up.setStyleSheet("QFrame {\n"
"    background-color: rgb(230, 52, 98);\n"
"    border:  None;\n"
"    border-radius: 10px;\n"
"}")
        self.notifications_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notifications_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notifications_up.setObjectName("notifications_up")
        self.notifications_oops_text = QtWidgets.QLabel(self.notifications_up)
        self.notifications_oops_text.setGeometry(QtCore.QRect(10, 5, 731, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(18)
        self.notifications_oops_text.setFont(font)
        self.notifications_oops_text.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.notifications_oops_text.setObjectName("notifications_oops_text")
        self.notifications_close = QtWidgets.QPushButton(self.notifications_up)
        self.notifications_close.setGeometry(QtCore.QRect(715, 10, 16, 16))
        self.notifications_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notifications_close.setStyleSheet("QPushButton {\n"
"    background: transparent\n"
"}")
        self.notifications_close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/aki_close_notify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notifications_close.setIcon(icon5)
        self.notifications_close.setIconSize(QtCore.QSize(13, 13))
        self.notifications_close.setObjectName("notifications_close")
        self.notifications_text = QtWidgets.QLabel(self.notifications_main_background)
        self.notifications_text.setGeometry(QtCore.QRect(10, 58, 721, 16))
        self.notifications_text.setStyleSheet("QLabel {\n"
"    color: #fff\n"
"}")
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(10)
        self.notifications_text.setFont(font)
        self.notifications_text.setObjectName("notifications_text")
        self.notifications_terms_of_use_background = QtWidgets.QFrame(self.notifications_dark_background)
        self.notifications_terms_of_use_background.setGeometry(QtCore.QRect(100, 60, 741, 461))
        self.notifications_terms_of_use_background.setStyleSheet("QFrame {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border:  None;\n"
"    border-radius: 10px;\n"
"}")
        self.notifications_terms_of_use_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notifications_terms_of_use_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notifications_terms_of_use_background.setObjectName("notifications_terms_of_use_background")
        self.notifications_terms_of_use_heading = QtWidgets.QLabel(self.notifications_terms_of_use_background)
        self.notifications_terms_of_use_heading.setGeometry(QtCore.QRect(0, 0, 731, 41))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(18)
        self.notifications_terms_of_use_heading.setFont(font)
        self.notifications_terms_of_use_heading.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"}")
        self.notifications_terms_of_use_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.notifications_terms_of_use_heading.setObjectName("notifications_terms_of_use_heading")
        self.notifications_terms_of_use_text = QtWidgets.QTextEdit(self.notifications_terms_of_use_background)
        self.notifications_terms_of_use_text.setGeometry(QtCore.QRect(10, 40, 715, 411))
        self.notifications_terms_of_use_text.setStyleSheet("QTextEdit {\n"
"    padding: 5px\n"
"}\n"
"\n"
"QScrollBar:vertical {              \n"
"    border: none;\n"
"    background: white;\n"
"    border-radius: 0px;\n"
"    width: 8px;           \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1,y2:0.523, stop:0 rgba(245, 112, 147, 255), stop:1 rgba(230, 52, 98, 255));\n"
"    min-height: 0px;\n"
"}")
        self.notifications_terms_of_use_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.notifications_terms_of_use_text.setReadOnly(True)
        self.notifications_terms_of_use_text.setObjectName("notifications_terms_of_use_text")
        self.notifications_terms_of_use_close = QtWidgets.QPushButton(self.notifications_terms_of_use_background)
        self.notifications_terms_of_use_close.setGeometry(QtCore.QRect(708, 10, 16, 16))
        self.notifications_terms_of_use_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notifications_terms_of_use_close.setStyleSheet("QPushButton {\n"
"    background: transparent\n"
"}")
        self.notifications_terms_of_use_close.setText("")
        self.notifications_terms_of_use_close.setIcon(icon5)
        self.notifications_terms_of_use_close.setIconSize(QtCore.QSize(13, 13))
        self.notifications_terms_of_use_close.setObjectName("notifications_terms_of_use_close")
        Aki_sign.setCentralWidget(self.centralwidget)

        self.retranslateUi(Aki_sign)
        self.sign_stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Aki_sign)

    def retranslateUi(self, Aki_sign):
        _translate = QtCore.QCoreApplication.translate
        Aki_sign.setWindowTitle(_translate("Aki_sign", "MainWindow"))
        self.logo_text.setText(_translate("Aki_sign", "AkiReworked"))
        self.auth_text.setText(_translate("Aki_sign", "Авторизация"))
        self.auth_login.setPlaceholderText(_translate("Aki_sign", "Имя пользователя"))
        self.auth_pass.setPlaceholderText(_translate("Aki_sign", "Пароль"))
        self.remember_me.setText(_translate("Aki_sign", "Запомнить меня"))
        self.forgot_pass.setText(_translate("Aki_sign", "Забыли пароль?"))
        self.not_account.setText(_translate("Aki_sign", "Нет аккаунта?"))
        self.auth_reg_btn.setText(_translate("Aki_sign", "Зарегистрироваться"))
        self.auth_sign.setText(_translate("Aki_sign", "Войти"))
        self.reg_terms_of_use_check.setText(_translate("Aki_sign", "Я согласен(на) с"))
        self.have_account.setText(_translate("Aki_sign", "Уже есть аккаунта?"))
        self.reg_login.setPlaceholderText(_translate("Aki_sign", "Имя пользователя"))
        self.reg_email.setPlaceholderText(_translate("Aki_sign", "E-mail"))
        self.reg_auth_btn.setText(_translate("Aki_sign", "Войти"))
        self.reg_sign.setText(_translate("Aki_sign", "Зарегистрироваться"))
        self.reg_text.setText(_translate("Aki_sign", "Регистрация"))
        self.reg_conditions.setText(_translate("Aki_sign", "условиями"))
        self.reg_terms_of_text2.setText(_translate("Aki_sign", "и"))
        self.reg_terms_of_use.setText(_translate("Aki_sign", "политикой"))
        self.reg_terms_of_use2.setText(_translate("Aki_sign", "конфеденциальности."))
        self.reg_pass.setPlaceholderText(_translate("Aki_sign", "Пароль"))
        self.reg_pass_2.setPlaceholderText(_translate("Aki_sign", "Повторите пароль"))
        self.aki_copyright.setText(_translate("Aki_sign", "Aki © 2021 Все права защищены"))
        self.notifications_oops_text.setText(_translate("Aki_sign", "Упс! Мы столкнулись с некоторыми проблемами."))
        self.notifications_text.setText(_translate("Aki_sign", "Тестовое сообщение. Пожалуйста, попробуйте ещё раз."))
        self.notifications_terms_of_use_heading.setText(_translate("Aki_sign", "Наши условия и политика конфиденциальности"))
        self.notifications_terms_of_use_text.setHtml(_translate("Aki_sign", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Ваша конфиденциальность важна для нас.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Эта политика конфиденциальности объясняет, какие персональные данные собирает и обрабатывает наше приложение &quot;Aki Passwords&quot;, как они обрабатываются и для каких целей они собираются и обрабатываются</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Какую информацию о вас мы собираем.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Типы данных, которые мы собираем и обрабатываем включают в себя следующее:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          1.Ваш никнейм в приложение.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          2.Ваш адрес электронной почты.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          3.Ваш IP-адрес.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Мы собираем некоторую или всю эту информацию в следующих случаях:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          1.Вы регистрируетесь как пользователь в нашем приложение</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          2.Вы используете это приложение.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Как используется Ваша личная информация.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Мы можем использовать Вашу личную информацию в следующих целях:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          1.Для того, чтобы сделать Вас зарегистрированным пользователем нашего приложения, чтобы Вы могли добавлять в него контент.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          2.Мы можем использовать Ваш адрес электронной почты, чтобы информировать Вас об активности в нашем приложение.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">          3.Ваш IP-адрес записывается при выполнении определённых действий в нашем приложение. Он никогда не отображается публично.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Обеспечение безопасности данных</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Мы стремимся обеспечить безопасность любой информации, которую Вы нам предоставляете.Чтобы предотвратить несанкционированный доступ или раскрытие информации, мы добавили подходящие меры и процедуры для защиты и обеспечения безопасности информации,которую мы собираем.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Принятие политики</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Дальнейшее использование нашего приложения означает Ваше полное согласие с этой политикой. Если Вы не согласны с нашей политикой, то пожалуйста, не используйте данное приложение. При регистрации мы также запросим Ваше явное согласие с политикой конфиденциальности.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Изменения в политике</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Мы можем вносить изменения в данную политику в любое время. Вам может быть предложено ознакомиться и повторно принять информацию в этой политике, если она изменится в будущем.</span></p></body></html>"))

