# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_splashscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aki_splashscreen(object):
    def setupUi(self, Aki_splashscreen):
        Aki_splashscreen.setObjectName("Aki_splashscreen")
        Aki_splashscreen.resize(684, 401)
        self.centralwidget = QtWidgets.QWidget(Aki_splashscreen)
        self.centralwidget.setObjectName("centralwidget")
        self.ss_background = QtWidgets.QFrame(self.centralwidget)
        self.ss_background.setGeometry(QtCore.QRect(10, 10, 660, 380))
        self.ss_background.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ss_background.setStyleSheet("QFrame {\n"
"    background-color:rgb(24, 24, 24);\n"
"    color:rgb(177, 177, 177);\n"
"    border-radius:  20px;\n"
"    border: None\n"
"}")
        self.ss_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ss_background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ss_background.setObjectName("ss_background")
        self.ss_label_title = QtWidgets.QLabel(self.ss_background)
        self.ss_label_title.setGeometry(QtCore.QRect(0, 60, 651, 51))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(40)
        self.ss_label_title.setFont(font)
        self.ss_label_title.setStyleSheet("color: rgb(230, 52, 98);")
        self.ss_label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.ss_label_title.setObjectName("ss_label_title")
        self.ss_label_description = QtWidgets.QLabel(self.ss_background)
        self.ss_label_description.setGeometry(QtCore.QRect(7, 120, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(18)
        self.ss_label_description.setFont(font)
        self.ss_label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.ss_label_description.setObjectName("ss_label_description")
        self.ss_progressBar = QtWidgets.QProgressBar(self.ss_background)
        self.ss_progressBar.setGeometry(QtCore.QRect(50, 280, 561, 23))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(8)
        self.ss_progressBar.setFont(font)
        self.ss_progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: #0e0e0e;\n"
"    color: rgb(177, 177, 177);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1,y2:0.523, stop:0 rgba(245, 112, 147, 255), stop:1 rgba(230, 52, 98, 255));\n"
"}")
        self.ss_progressBar.setProperty("value", 24)
        self.ss_progressBar.setObjectName("ss_progressBar")
        self.label_loading = QtWidgets.QLabel(self.ss_background)
        self.label_loading.setGeometry(QtCore.QRect(-1, 310, 661, 21))
        font = QtGui.QFont()
        font.setFamily("Acrom")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.ss_copyright = QtWidgets.QLabel(self.ss_background)
        self.ss_copyright.setGeometry(QtCore.QRect(54, 349, 561, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.ss_copyright.setFont(font)
        self.ss_copyright.setStyleSheet("")
        self.ss_copyright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ss_copyright.setObjectName("ss_copyright")
        Aki_splashscreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Aki_splashscreen)
        QtCore.QMetaObject.connectSlotsByName(Aki_splashscreen)

    def retranslateUi(self, Aki_splashscreen):
        _translate = QtCore.QCoreApplication.translate
        Aki_splashscreen.setWindowTitle(_translate("Aki_splashscreen", "MainWindow"))
        self.ss_label_title.setText(_translate("Aki_splashscreen", "<strong>AKI</strong> REWORKED"))
        self.ss_label_description.setText(_translate("Aki_splashscreen", "<html><head/><body><p><span style=\" font-weight:600;\">ADMIN PANEL</span></p></body></html>"))
        self.label_loading.setText(_translate("Aki_splashscreen", "loading..."))
        self.ss_copyright.setText(_translate("Aki_splashscreen", "Aki © 2021 Все права защищены"))
